[pytest]
markers =
    esprit: requires a running Esprit installation/API
    hardware: requires attached detector hardware
testpaths =
    tests

# run unit tests: pytest tests/bruker/unit
# run esprit integration tests: pytest -m esprit tests/bruker/integration
# run Bruker simulator tests: set PYTRIBEAM_BRUKER_TEST_ENV=simulator && pytest -m "esprit and not hardware" tests/bruker/integration
# run Bruker true-hardware tests: set PYTRIBEAM_BRUKER_TEST_ENV=hardware && set PYTRIBEAM_RUN_BRUKER_HARDWARE=1 && pytest -m "esprit and hardware" tests/bruker/hardware