"""
Lightweight package and environment metadata.

This module is intentionally safe to import in documentation builds and
installation checks. It must not import pytribeam.constants, pytribeam.types,
AutoScript runtime modules, Laser.PythonControl, workflow, or GUI modules.
"""

from importlib import metadata as md
from importlib.util import find_spec
from typing import Final, Optional, Tuple

MODULE_SHORT_NAME: Final[str] = "pytribeam"

AUTOSCRIPT_IMPORT_NAME: Final[str] = "autoscript_sdb_microscope_client"
AUTOSCRIPT_DIST_NAME: Final[str] = "autoscript-sdb-microscope-client"

LASER_IMPORT_NAME: Final[str] = "Laser"
LASER_PYTHONCONTROL_IMPORT_NAME: Final[str] = "Laser.PythonControl"
LASER_DIST_NAME: Final[str] = "Laser"

SUPPORTED_AUTOSCRIPT_VERSIONS: Final[Tuple[str, ...]] = (
    "4.8.1",
    "4.10.0",
    "4.11.0",
    # "4.13.1",
)

SUPPORTED_LASER_API_VERSIONS: Final[Tuple[str, ...]] = ("2.2.1",)

# Replace this with your actual current schema version.
YML_SCHEMA_VERSION: Final[str] = "1.0"


def get_version_or_none(dist_name: str) -> Optional[str]:
    """
    Return the installed distribution version, or None if it is not installed.

    This reads Python package metadata and does not import the runtime package.
    """
    try:
        return md.version(dist_name)
    except md.PackageNotFoundError:
        return None


def import_available(import_name: str) -> bool:
    """
    Return True if the import package appears importable.
    """
    try:
        return find_spec(import_name) is not None
    except (ImportError, ModuleNotFoundError, AttributeError, ValueError):
        return False


def get_pytribeam_version() -> Optional[str]:
    """
    Return the pytribeam version.

    Prefer the generated _version.py file, because it may contain release/dev
    information generated by vcs-versioning. Fall back to installed package
    metadata if needed.
    """
    try:
        from pytribeam._version import version

        return version
    except Exception:
        return get_version_or_none(MODULE_SHORT_NAME)


def get_pytribeam_commit_id() -> Optional[str]:
    """
    Return the pytribeam git commit identifier, if available.

    The generated _version.py may expose commit_id, __commit_id__, or
    __git_commit__ depending on the release/versioning path.
    """
    try:
        import pytribeam._version as version_mod

        commit = getattr(version_mod, "commit_id", None)
        if commit:
            return commit

        commit = getattr(version_mod, "__commit_id__", None)
        if commit:
            return commit

        commit = getattr(version_mod, "__git_commit__", None)
        if commit:
            return commit

        return None
    except Exception:
        return None


def get_autoscript_version() -> Optional[str]:
    """
    Return the installed AutoScript distribution version, if detected.
    """
    return get_version_or_none(AUTOSCRIPT_DIST_NAME)


def get_laser_api_version() -> Optional[str]:
    """
    Return the installed Laser API distribution version, if detected.
    """
    return get_version_or_none(LASER_DIST_NAME)


def autoscript_available() -> bool:
    """
    Return True if the AutoScript import package appears available.
    """
    return import_available(AUTOSCRIPT_IMPORT_NAME)


def laser_api_available() -> bool:
    """
    Return True if the Laser API top-level import package appears available.
    """
    return import_available(LASER_IMPORT_NAME)


def laser_pythoncontrol_available() -> bool:
    """
    Return True if Laser.PythonControl appears available.
    """
    return import_available(LASER_PYTHONCONTROL_IMPORT_NAME)
