# file generated by vcs-versioning
# do not edit manually — bumped by prepare-release.yml ahead of tagging a release
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '0.1.2.dev0'
__version_tuple__ = version_tuple = (0, 1, 2, 'dev0')

__commit_id__ = commit_id = None
# exact commit: see the git tag matching this version (git rev-list -n1 vX.Y.Z)
