#!/usr/bin/python3
"""
Experiment log-file utilities for `pytribeam`.

This module provides helper functions for creating and updating `pytribeam`
experiment log files. Logs are stored as HDF5 files using `h5py`, with dataset
names, structured NumPy dtypes, and units defined by `pytribeam.constants.Constants`.

The logging functions append timestamped rows to HDF5 datasets for experiment
settings, stage position, laser power, and specimen current. These records are
used to document experiment state before, during, and after automated
TriBeam/FIB/laser operations.

## Typical usage

```python
from pathlib import Path

from pytribeam import log
from pytribeam.constants import Constants

log_path = Path("experiment_log.h5")
config_path = Path("experiment.yml")

log.create_file(log_path)

log.experiment_settings(
    slice_number=1,
    step_number=1,
    log_filepath=log_path,
    yml_path=config_path,
)

log.position(
    step_number=1,
    step_name="mill",
    slice_number=1,
    log_filepath=log_path,
    dataset_name=Constants.pre_position_dataset_name,
    current_position=current_position,
)
```

## Main entry points

- `create_file`: create an HDF5 log file if it does not already exist.
- `current_time`: return the current time as a `tbt.TimeStamp`.
- `experiment_settings`: append the active experiment configuration to the log.
- `position`: append a stage-position record to a step-specific dataset.
- `laser_power`: append a laser-power measurement to a step-specific dataset.
- `specimen_current`: append a specimen-current measurement to a step-specific
  dataset.
- `yml_from_log`: extract a saved YAML configuration from an existing log file.

## Log-file layout

Experiment settings are stored in a top-level dataset named by
`Constants.settings_dataset_name`.

Step-specific measurements are stored under groups named using the step number
and step name:

```text
{step_number:02d}_{step_name}/{dataset_name}
```

For example:

```text
Experiment Settings
01_mill/Position Before
01_mill/Position After
01_laser/Laser Power Before
01_laser/Laser Power After
```

The exact dataset names and structured dtypes are defined in
`pytribeam.constants.Constants`.

## Timestamp convention

Each logged row includes both a human-readable timestamp and a UNIX timestamp.
Timestamps are generated by `current_time` at the time the row is written.

## Units

Datasets that store physical quantities include HDF5 attributes describing their
units. Stage positions are recorded in millimeters and degrees, laser power is
recorded in watts, and specimen current is recorded in nanoamperes.

## Notes

This module assumes that log files are valid HDF5 files. Use `create_file` to
initialize new log files before appending records.

<hr style="height: 12px; background-color: #333; border: none;">
"""

__all__ = [
    "create_file",
    "current_time",
    "yml_from_log",
    "experiment_settings",
    "position",
    "laser_power",
    "specimen_current",
]

# Default python modules
# from functools import singledispatch
from pathlib import Path
import datetime

# Autoscript included modules
import numpy as np
import h5py

# 3rd party module

# Local scripts
from pytribeam.constants import Constants
import pytribeam.types as tbt


def create_file(path: Path) -> bool:
    """
    Create a log file at the specified path.

    This function creates a log file at the specified path if it does not already exist.

    ## Parameters

    - `path` (`Path`): The path where the log file should be created.

    ## Returns

    - `bool`: True if the log file is created successfully.

    ## Raises

    - `ValueError`: If the log file cannot be created.
    """
    if not path.is_file():
        log = h5py.File(path, "w")
        log.close()
        if path.is_file():
            print(f'Logfile created at "{path}".')
    if path.is_file():
        return True
    raise ValueError(f'Unable to create log file at location "{path}".')


def current_time() -> tbt.TimeStamp:
    """
    Get the current time as a timestamp.

    This function returns the current time as a `TimeStamp` object, including both human-readable and UNIX time formats.

    ## Returns

    - `tbt.TimeStamp`: The current time as a `TimeStamp` object.
    """
    now = datetime.datetime.now()
    human_readable = now.strftime("%m/%d/%Y %H:%M:%S")
    unix_time = int(now.timestamp())
    time = tbt.TimeStamp(human_readable=human_readable, unix=unix_time)
    return time


def yml_from_log(
    log_path_h5: Path,
    output_path_yml: Path,
    row: int,
    config_field: str = "Config File",
) -> bool:
    """
    Extract YAML configuration from a log file and save it to an output path.

    This function extracts the YAML configuration from a specified row in the log file and saves it to the output path.

    ## Parameters

    - `log_path_h5` (`Path`): The path to the log file.
    - `output_path_yml` (`Path`): The path to save the extracted YAML configuration.
    - `row` (`int`): The row number to extract the configuration from.
    - `config_field` (`str, optional`): The field name for the configuration in the log file (default is "Config File").

    ## Returns

    - `bool`: True if the YAML configuration is extracted and saved successfully.
    """
    # TODO enforce file formats on inputs
    with h5py.File(log_path_h5, "r") as file:
        data = np.array(file[Constants.settings_dataset_name][:])
    settings = data[row][Constants.settings_dtype.names.index(config_field)].decode(
        "utf-8"
    )

    with open(output_path_yml, "w") as file:
        file.write(settings)

    return True


def experiment_settings(
    slice_number: int,
    step_number: int,
    log_filepath: Path,
    yml_path: Path,
) -> bool:
    """
    Log experiment settings to the log file.

    This function logs the experiment settings from a YAML file to the log file.

    ## Parameters

    - `slice_number` (`int`): The slice number for the experiment.
    - `step_number` (`int`): The step number for the experiment.
    - `log_filepath` (`Path`): The path to the log file.
    - `yml_path` (`Path`): The path to the YAML file containing the experiment settings.

    ## Returns

    - `bool`: True if the experiment settings are logged successfully.
    """
    dataset_name = Constants.settings_dataset_name
    settings_dtype = Constants.settings_dtype
    time = current_time()

    with open(yml_path, "r") as yml_file:
        yml_data = yml_file.read()

    if not log_filepath.exists():
        log_filepath.touch()

    with h5py.File(log_filepath, "r+") as log:
        if not dataset_name in log:
            settings = log.create_dataset(
                dataset_name,
                (0,),
                settings_dtype,
                maxshape=(None,),
            )
        dataset = log[dataset_name]
        settings_data = np.array(
            [
                (
                    slice_number,
                    step_number,
                    yml_data,
                    time.human_readable,
                    time.unix,
                )
            ],
            settings_dtype,
        )
        # add one row to table
        dataset.resize(dataset.shape[0] + 1, axis=0)
        dataset[-1:] = settings_data

    return True


def position(
    step_number: int,
    step_name: str,
    slice_number: int,
    log_filepath: Path,
    dataset_name: str,
    current_position: tbt.StagePositionUser,
) -> bool:
    """
    Log the current position to the log file.

    This function logs the current position of the stage to the log file.

    ## Parameters

    - `step_number` (`int`): The step number for the experiment.
    - `step_name` (`str`): The name of the step.
    - `slice_number` (`int`): The slice number for the experiment.
    - `log_filepath` (`Path`): The path to the log file.
    - `dataset_name` (`str`): The name of the dataset to log the position to.
    - `current_position` (`tbt.StagePositionUser`): The current position of the stage.

    ## Returns

    - `bool`: True if the current position is logged successfully.
    """
    print("\tLogging current position...")
    dataset_location = f"{step_number:02d}_{step_name}/{dataset_name}"
    time = current_time()

    with h5py.File(log_filepath, "r+") as file:
        if not dataset_location in file:
            position = file.create_dataset(
                dataset_location,
                (0,),
                Constants.position_dtype,
                maxshape=(None,),
            )
            position.attrs["X Units"] = np.string_("[mm]")
            position.attrs["Y Units"] = np.string_("[mm]")
            position.attrs["Z Units"] = np.string_("[mm]")
            position.attrs["T Units"] = np.string_("[degrees]")
            position.attrs["R Units"] = np.string_("[degrees]")

        dataset = file[dataset_location]
        position_data = np.array(
            [
                (
                    slice_number,
                    round(current_position.x_mm, 6),
                    round(current_position.y_mm, 6),
                    round(current_position.z_mm, 6),
                    round(current_position.t_deg, 6),
                    round(current_position.r_deg, 6),
                    time.human_readable,
                    time.unix,
                )
            ],
            Constants.position_dtype,
        )
        # add one row to table
        dataset.resize(dataset.shape[0] + 1, axis=0)
        dataset[-1:] = position_data

    return True


def laser_power(
    step_number: int,
    step_name: str,
    slice_number: int,
    log_filepath: Path,
    dataset_name: str,
    power_w: float,
) -> bool:
    """
    Log the laser power to the log file.

    This function logs the laser power to the log file.

    ## Parameters

    - `step_number` (`int`): The step number for the experiment.
    - `step_name` (`str`): The name of the step.
    - `slice_number` (`int`): The slice number for the experiment.
    - `log_filepath` (`Path`): The path to the log file.
    - `dataset_name` (`str`): The name of the dataset to log the laser power to.
    - `power_w` (`float`): The laser power in watts.

    ## Returns

    - `bool`: True if the laser power is logged successfully.
    """
    print("\tLogging laser power...")
    dataset_location = f"{step_number:02d}_{step_name}/{dataset_name}"
    time = current_time()

    with h5py.File(log_filepath, "r+") as file:
        if not dataset_location in file:
            laser_power = file.create_dataset(
                dataset_location,
                (0,),
                Constants.laser_power_dtype,
                maxshape=(None,),
            )
            laser_power.attrs["Units"] = np.string_("[W]")

        dataset = file[dataset_location]
        laser_power_data = np.array(
            [
                (
                    slice_number,
                    round(power_w, 6),
                    time.human_readable,
                    time.unix,
                )
            ],
            Constants.laser_power_dtype,
        )
        # add one row to table
        dataset.resize(dataset.shape[0] + 1, axis=0)
        dataset[-1:] = laser_power_data

    return True


def specimen_current(
    step_number: int,
    step_name: str,
    slice_number: int,
    log_filepath: Path,
    dataset_name: str,
    specimen_current_na: float,
) -> bool:
    """
    Log the specimen current to the log file.

    This function logs the specimen current to the log file.

    ## Parameters

    - `step_number` (`int`): The step number for the experiment.
    - `step_name` (`str`): The name of the step.
    - `slice_number` (`int`): The slice number for the experiment.
    - `log_filepath` (`Path`): The path to the log file.
    - `dataset_name` (`str`): The name of the dataset to log the specimen current to.
    - `specimen_current_na` (`float`): The specimen current in nanoamperes.

    ## Returns

    - `bool`: True if the specimen current is logged successfully.
    """
    print("\tLogging sample current...")
    dataset_location = f"{step_number:02d}_{step_name}/{dataset_name}"
    time = current_time()

    with h5py.File(log_filepath, "r+") as file:
        if not dataset_location in file:
            specimen_current = file.create_dataset(
                dataset_location,
                (0,),
                Constants.specimen_current_dtype,
                maxshape=(None,),
            )
            specimen_current.attrs["Units"] = np.string_("[nA]")

        dataset = file[dataset_location]
        specimen_current_data = np.array(
            [
                (
                    slice_number,
                    round(specimen_current_na, 6),
                    time.human_readable,
                    time.unix,
                )
            ],
            Constants.specimen_current_dtype,
        )
        # add one row to table
        dataset.resize(dataset.shape[0] + 1, axis=0)
        dataset[-1:] = specimen_current_data
    print("\tLogging sample current complete...")

    return True
